name: remote ssh command
on:
  pull_request:
  push: 
    branches:
      - "main"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Deploy to aws
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /var/www/Laravel
          git config pull.rebase false
          sudo git pull
          sudo COMPOSER_ALLOW_SUPERUSER=1 composer install
          sudo mysql -u root -p laravel < seed.sql
          sudo mysql -u root -p${{ secrets.MYSQL_PASSWORD }} laravel < seed.sql
          sudo apt-get install apache2
          sudo systemctl restart apache2