name: remote ssh command
on:
  pull_request:
  push: 
    branches:
      - "main"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Deploy to aws
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /var/www/Laravel
          sudo -u www-data git pull origin main
          sudo -u www-data composer install
          sudo -u www-data php artisan migrate
          sudo -u www-data php artisan config:cache
          sudo -u www-data php artisan route:cache
          sudo -u www-data php artisan view:cache
          sudo systemctl restart apache2